<a href="https://colab.research.google.com/github/ascordero001-cell/enares-2024-crs04-ml/blob/main/notebooks/02%20bigquery/06_ENARES_2024_STAGE2_documentation_and_profiling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 06_ENARES_2024_STAGE2_documentation_and_profiling.ipynb

**Proyecto:** ENARES 2024 - Módulo CRS04  
**Stage:** 02  
**Objetivo:** generar documentación técnica y profiling de solo lectura para el anexo integrado de Sprint y Competencias.

## Issues cubiertos

- **Issue #12:** Documento de diseño lógico/físico y ERD.
- **Issue #13:** Estrategia de particionamiento BigQuery, solo documentación.
- **Issue #14:** Data profiling de solo lectura.
- **Issue #15:** Documento de arquitectura de seguridad.

## Regla Stage 02

Este notebook **no hace merge**, **no recodifica**, **no crea indicadores**, **no modela** y **no interpreta resultados estadísticos**.  
Solo genera documentación y perfiles técnicos sobre tablas raw ya cargadas.

In [ ]:
# ============================================================
# 0. Instalación, autenticación y configuración común
# ============================================================

!pip install -q google-cloud-bigquery pandas pandas-gbq pyarrow ydata-profiling

from google.colab import auth, drive
from google.cloud import bigquery
from datetime import datetime, timezone
import pandas as pd
import os

try:
    from ydata_profiling import ProfileReport
except Exception as exc:
    raise ImportError(
        "No se pudo importar ydata_profiling. Re-ejecuta la celda de instalación."
    ) from exc

auth.authenticate_user()
drive.mount("/content/drive")

PROJECT_ID = os.environ.get("PROJECT_ID") or input("Enter Google Cloud PROJECT_ID: ").strip()
if not PROJECT_ID:
    raise ValueError("PROJECT_ID no puede estar vacío.")

LOCATION = "US"

ROOT_DRIVE = "/content/drive/MyDrive/ENARES_2024_PROJECT"
LOG_DIR = f"{ROOT_DRIVE}/05Resultados/logs"
DOCS_DIR = f"{ROOT_DRIVE}/docs"

os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(DOCS_DIR, exist_ok=True)

RUN_UTC = datetime.now(timezone.utc).isoformat()

RAW_DATASET = "enares2024_crs04_raw"

RAW_TABLES = [
    "raw_crs04_cap100",
    "raw_crs04_cap200",
    "raw_crs04_cap248",
    "raw_crs04_cap300",
]

RAW_TABLE_SPECS = {
    "raw_crs04_cap100": {
        "source_file": "19_CRS04_CAP100.sav",
        "expected_rows": 18807,
        "expected_columns": 147,
    },
    "raw_crs04_cap200": {
        "source_file": "20_CRS04_CAP200.sav",
        "expected_rows": 18807,
        "expected_columns": 523,
    },
    "raw_crs04_cap248": {
        "source_file": "21_CRS04_CAP248.sav",
        "expected_rows": 18807,
        "expected_columns": 578,
    },
    "raw_crs04_cap300": {
        "source_file": "22_CRS04_CAP300.sav",
        "expected_rows": 18807,
        "expected_columns": 51,
    },
}

client = bigquery.Client(project=PROJECT_ID, location=LOCATION)

print("PROJECT_ID:", PROJECT_ID)
print("LOCATION:", LOCATION)
print("LOG_DIR:", LOG_DIR)
print("DOCS_DIR:", DOCS_DIR)
print("RUN_UTC:", RUN_UTC)
print("Notebook 06 initialized.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 1.9 MB/s eta 0:00:00

/tmp/ipykernel_17938/1637617379.py:14: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Mounted at /content/drive
Enter Google Cloud PROJECT_ID: 	enares-2024-crs04
PROJECT_ID: enares-2024-crs04
LOCATION: US
LOG_DIR: /content/drive/MyDrive/ENARES_2024_PROJECT/05Resultados/logs
DOCS_DIR: /content/drive/MyDrive/ENARES_2024_PROJECT/docs
RUN_UTC: 2026-06-19T23:31:36.990760+00:00
Notebook 06 initialized.

## 1. Control metodológico

Deja evidencia explícita de que este notebook se limita a documentación y profiling de solo lectura.

In [ ]:
stage06_policy = pd.DataFrame([{
    "stage": "STAGE02",
    "notebook": "06_ENARES_2024_STAGE2_documentation_and_profiling.ipynb",
    "allowed_actions": "technical_documentation; security_documentation; read_only_profiling; closure_reporting",
    "forbidden_actions": "merge; recode; derived_variables; indicators; statistical_models; substantive_interpretation",
    "raw_data_write_operations": False,
    "checked_at_utc": RUN_UTC,
}])

stage06_policy_output = f"{LOG_DIR}/ENARES_2024_STAGE2_documentation_profiling_policy.csv"
stage06_policy.to_csv(stage06_policy_output, index=False)

display(stage06_policy)
print("Saved:", stage06_policy_output)

,stage,notebook,allowed_actions,forbidden_actions,raw_data_write_operations,checked_at_utc
0,STAGE02,06_ENARES_2024_STAGE2_documentation_and_profil...,technical_documentation; security_documentatio...,merge; recode; derived_variables; indicators; ...,False,2026-06-19T23:31:36.990760+00:00

Saved: /content/drive/MyDrive/ENARES_2024_PROJECT/05Resultados/logs/ENARES_2024_STAGE2_documentation_profiling_policy.csv

## 2. Issue #12 — Documento de diseño lógico/físico y ERD

Genera `ENARES_2024_STAGE2_CRS04_ERD.md` en `docs/`.

In [ ]:
erd_markdown = f"""# ENARES 2024 CRS04 - Diseño Lógico/Físico y ERD

Fecha UTC: {RUN_UTC}

## Alcance

Este documento pertenece a Stage 02. Su objetivo es documentar la estructura raw de CRS04 y la hipótesis de llave para validación posterior.

Stage 02 no ejecuta merge analítico, no recodifica variables, no crea indicadores, no modela y no interpreta resultados estadísticos.

## Tablas raw CRS04

| Archivo fuente | Tabla BigQuery raw | Filas esperadas | Columnas esperadas |
|---|---:|---:|---:|
| 19_CRS04_CAP100.sav | raw_crs04_cap100 | 18807 | 147 |
| 20_CRS04_CAP200.sav | raw_crs04_cap200 | 18807 | 523 |
| 21_CRS04_CAP248.sav | raw_crs04_cap248 | 18807 | 578 |
| 22_CRS04_CAP300.sav | raw_crs04_cap300 | 18807 | 51 |

## ERD

La hipótesis documental de llave es la compuesta `ID + COLEGIAL_ID`. CAP100 funciona como tabla base de referencia para el merge analítico posterior.

La validación formal de unicidad, missing, duplicados y match entre capítulos corresponde a Stage 03, no a Stage 02.

```mermaid
erDiagram
    CRS04_RAW_CAP100 {{
        int ID PK
        int COLEGIAL_ID PK
        string CCDD
        int anio_encuesta
    }}
    CRS04_RAW_CAP200 {{
        int ID PK, FK
        int COLEGIAL_ID PK, FK
        int anio_encuesta
    }}
    CRS04_RAW_CAP248 {{
        int ID PK, FK
        int COLEGIAL_ID PK, FK
        int anio_encuesta
    }}
    CRS04_RAW_CAP300 {{
        int ID PK, FK
        int COLEGIAL_ID PK, FK
        int anio_encuesta
    }}
    CRS04_RAW_CAP100 ||--|| CRS04_RAW_CAP200 : "ID + COLEGIAL_ID"
    CRS04_RAW_CAP100 ||--|| CRS04_RAW_CAP248 : "ID + COLEGIAL_ID"
    CRS04_RAW_CAP100 ||--|| CRS04_RAW_CAP300 : "ID + COLEGIAL_ID"
```

## Nota metodológica

La llave no se asume como válida: se documenta como hipótesis. Su demostración pertenece a Stage 03.

En Stage 02 solo se preservan microdatos raw, metadata SPSS/PDF y evidencias de trazabilidad.
"""

erd_output = f"{DOCS_DIR}/ENARES_2024_STAGE2_CRS04_ERD.md"

with open(erd_output, "w", encoding="utf-8") as f:
    f.write(erd_markdown)

print("Issue #12 document saved:", erd_output)

Issue #12 document saved: /content/drive/MyDrive/ENARES_2024_PROJECT/docs/ENARES_2024_STAGE2_CRS04_ERD.md

## 3. Issue #13 — Estrategia de particionamiento BigQuery

Genera `ENARES_2024_STAGE2_partitioning_strategy.md` en `docs/`.

Importante: en Stage 02 solo se documenta la estrategia. No se crean tablas particionadas ni variables derivadas.

In [ ]:
partitioning_markdown = f"""# ENARES 2024 CRS04 - Stage 2 Estrategia de Particionamiento

Fecha UTC: {RUN_UTC}

## Alcance de Stage 02

Stage 02 solo documenta esta estrategia. No crea tablas particionadas ni variables derivadas sobre la capa raw.

La implementación física se difiere a Stage 03 sobre capas `cleaned` o `analytical`.

## Razón metodológica

Crear una variable derivada como `fecha_encuesta_referencia` en Stage 02 violaría el límite metodológico de la fase, porque Stage 02 no crea variables derivadas.

Crear tablas `*_partitioned` dentro de la capa raw también contaminaría la preservación intacta de microdatos.

## Estrategia recomendada

- Clave lógica de particionamiento futura: `anio_encuesta`.
- Si solo existe un año, como 2024, particionar por DATE genera una sola partición y no aporta poda ni ahorro.
- Para un único año se recomienda considerar `CLUSTER BY` sobre columnas de consulta frecuente.
- Para múltiples años se recomienda `PARTITION BY RANGE_BUCKET(anio_encuesta, GENERATE_ARRAY(2020, 2030, 1))`.
- Cualquier casting debe usar `SAFE_CAST` para tolerar valores nulos o no numéricos.

## SQL de referencia para Stage 03

```sql
-- Ejecutar solo en Stage 03 sobre capa cleaned/analytical, no sobre raw.

CREATE OR REPLACE TABLE `PROJECT_ID.enares2024_crs04_cleaned.crs04_cap100`
PARTITION BY RANGE_BUCKET(anio_encuesta, GENERATE_ARRAY(2020, 2030, 1))
AS
SELECT *
FROM `PROJECT_ID.enares2024_crs04_cleaned.crs04_cap100_staging`;
```

## Justificación técnica

El particionamiento reduce bytes procesados cuando las consultas filtran por la columna de partición. Para evaluar costo y rendimiento se debe registrar `total_bytes_processed`, `total_bytes_billed`, `slot_millis` y `cache_hit`.

En Stage 02 la evidencia se limita a documentación, observabilidad de tablas raw y cierre de competencia.
"""

partitioning_output = f"{DOCS_DIR}/ENARES_2024_STAGE2_partitioning_strategy.md"

with open(partitioning_output, "w", encoding="utf-8") as f:
    f.write(partitioning_markdown)

print("Issue #13 document saved:", partitioning_output)

Issue #13 document saved: /content/drive/MyDrive/ENARES_2024_PROJECT/docs/ENARES_2024_STAGE2_partitioning_strategy.md

## 4. Issue #15 — Arquitectura de seguridad

Genera `ENARES_2024_STAGE2_security_architecture.md` en `docs/`.

In [ ]:
security_markdown = f"""# ENARES 2024 CRS04 - Stage 2 Security Architecture

Fecha UTC: {RUN_UTC}

## Alcance

Este documento describe controles mínimos de seguridad para Stage 02, enfocados en autenticación, autorización, cifrado en tránsito y protección de microdatos.

## Autenticación

En ejecución interactiva de Colab se utiliza autenticación de usuario mediante OAuth 2.0.

Para ejecuciones automatizadas se recomienda Service Account con permisos mínimos y rotación controlada de credenciales.

## IAM mínimo privilegio

La cuenta de ejecución debe tener únicamente los permisos necesarios para Stage 02:

- Lectura sobre fuentes autorizadas.
- Escritura solo sobre datasets Stage 02 requeridos.
- Lectura de tablas raw y metadata para validación.
- Sin permisos Owner o Editor a nivel proyecto.
- Sin credenciales persistidas en notebooks, repositorios ni outputs.

## Cifrado en tránsito

La comunicación con Google Cloud APIs, BigQuery, Cloud Storage y Google Drive debe realizarse mediante HTTPS/TLS.

## Protección de microdatos

Los microdatos ENARES se tratan como información sensible.

Stage 02:

- No publica microdatos.
- No genera resultados agregados públicos.
- No expone credenciales.
- No realiza modelamiento ni interpretación estadística.
- Preserva datos raw y metadata con trazabilidad.

## Gobernanza y auditoría

La gobernanza se evidencia mediante:

- Inventario de tablas raw.
- Validación de filas y columnas.
- Metadata SPSS preservada.
- Metadata documental PDF.
- SHA-256 de fuentes.
- Observabilidad de tablas.
- Checks de cierre reproducibles.

## Recomendación operativa

Para pasar de ejecución académica/interactiva a pipeline productivo, reemplazar autenticación manual de Colab por Service Account con IAM mínimo privilegio y registrar los roles exactos asignados.
"""

security_output = f"{DOCS_DIR}/ENARES_2024_STAGE2_security_architecture.md"

with open(security_output, "w", encoding="utf-8") as f:
    f.write(security_markdown)

print("Issue #15 document saved:", security_output)

Issue #15 document saved: /content/drive/MyDrive/ENARES_2024_PROJECT/docs/ENARES_2024_STAGE2_security_architecture.md

## 5. Verificación de documentos generados

Valida que los documentos de #12, #13 y #15 existan.

In [ ]:
documentation_outputs = [
    "ENARES_2024_STAGE2_CRS04_ERD.md",
    "ENARES_2024_STAGE2_partitioning_strategy.md",
    "ENARES_2024_STAGE2_security_architecture.md",
]

doc_rows = []

for filename in documentation_outputs:
    path = f"{DOCS_DIR}/{filename}"
    doc_rows.append({
        "filename": filename,
        "path": path,
        "exists": os.path.exists(path),
        "size_bytes": os.path.getsize(path) if os.path.exists(path) else None,
        "checked_at_utc": RUN_UTC,
    })

documentation_check = pd.DataFrame(doc_rows)

documentation_check_output = f"{LOG_DIR}/ENARES_2024_STAGE2_documentation_check.csv"
documentation_check.to_csv(documentation_check_output, index=False)

display(documentation_check)

if not documentation_check["exists"].all():
    missing = documentation_check.loc[~documentation_check["exists"], "filename"].tolist()
    raise FileNotFoundError("Faltan documentos Stage 02: " + ", ".join(missing))

print("Documentation checks PASS")
print("Saved:", documentation_check_output)

,filename,path,exists,size_bytes,checked_at_utc
0,ENARES_2024_STAGE2_CRS04_ERD.md,/content/drive/MyDrive/ENARES_2024_PROJECT/doc...,True,1911,2026-06-19T23:31:36.990760+00:00
1,ENARES_2024_STAGE2_partitioning_strategy.md,/content/drive/MyDrive/ENARES_2024_PROJECT/doc...,True,1850,2026-06-19T23:31:36.990760+00:00
2,ENARES_2024_STAGE2_security_architecture.md,/content/drive/MyDrive/ENARES_2024_PROJECT/doc...,True,1835,2026-06-19T23:31:36.990760+00:00

Documentation checks PASS
Saved: /content/drive/MyDrive/ENARES_2024_PROJECT/05Resultados/logs/ENARES_2024_STAGE2_documentation_check.csv

## 6. Issue #14 — Profiling de solo lectura

Genera perfiles HTML con `ydata-profiling`.

Para evitar problemas de memoria en Colab, se usa una muestra configurable por tabla. El profiling es de solo lectura porque solo ejecuta `SELECT` sobre BigQuery y guarda HTML local en Drive.

Si deseas perfilar todas las filas, cambia `PROFILE_LIMIT` a `None`.

In [ ]:
# ============================================================
# Configuración de profiling
# ============================================================

PROFILE_LIMIT = 5000  # cambiar a None para todas las filas, si Colab tiene memoria suficiente

profiling_log = []

for table_name in RAW_TABLES:
    print("\nProfiling table:", table_name)

    table_ref = f"{PROJECT_ID}.{RAW_DATASET}.{table_name}"

    rowcount_before = client.query(
        f"SELECT COUNT(*) AS n FROM `{table_ref}`"
    ).result().to_dataframe()["n"].iloc[0]

    # Verificar si existe anio_encuesta antes de filtrar.
    table = client.get_table(table_ref)
    schema_names = {field.name for field in table.schema}

    if "anio_encuesta" in schema_names:
        where_clause = "WHERE anio_encuesta = 2024"
    else:
        where_clause = ""

    limit_clause = f"LIMIT {PROFILE_LIMIT}" if PROFILE_LIMIT is not None else ""

    query = f'''
    SELECT *
    FROM `{table_ref}`
    {where_clause}
    {limit_clause}
    '''

    df = client.query(query).result().to_dataframe()

    if df.empty:
        raise ValueError(f"Profiling query returned 0 rows for {table_name}")

    profile = ProfileReport(
        df,
        title=f"ENARES 2024 CRS04 - {table_name}",
        minimal=True,
    )

    profile_output = f"{LOG_DIR}/ENARES_2024_STAGE2_profile_{table_name}.html"
    profile.to_file(profile_output)

    rowcount_after = client.query(
        f"SELECT COUNT(*) AS n FROM `{table_ref}`"
    ).result().to_dataframe()["n"].iloc[0]

    profiling_log.append({
        "table_name": table_name,
        "table_ref": table_ref,
        "profile_limit": PROFILE_LIMIT,
        "profiled_rows": len(df),
        "rowcount_before": rowcount_before,
        "rowcount_after": rowcount_after,
        "raw_data_unchanged": rowcount_before == rowcount_after,
        "profile_output": profile_output,
        "profile_exists": os.path.exists(profile_output),
        "profile_size_bytes": os.path.getsize(profile_output) if os.path.exists(profile_output) else None,
        "checked_at_utc": RUN_UTC,
    })

profiling_validation = pd.DataFrame(profiling_log)

profiling_validation_output = f"{LOG_DIR}/ENARES_2024_STAGE2_profiling_validation.csv"
profiling_validation.to_csv(profiling_validation_output, index=False)

display(profiling_validation)

if not profiling_validation["raw_data_unchanged"].all():
    raise AssertionError("Profiling no cumple modo solo lectura: cambiaron conteos.")

if not profiling_validation["profile_exists"].all():
    missing_profiles = profiling_validation.loc[~profiling_validation["profile_exists"], "table_name"].tolist()
    raise FileNotFoundError("Faltan perfiles HTML: " + ", ".join(missing_profiles))

print("Issue #14 profiling PASS")
print("Saved:", profiling_validation_output)

Profiling table: raw_crs04_cap100

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/147 [00:00<?, ?it/s]
  4%|▍         | 6/147 [00:00<00:02, 51.28it/s]
  8%|▊         | 12/147 [00:00<00:03, 42.06it/s]
 14%|█▍        | 21/147 [00:00<00:02, 56.94it/s]
 21%|██        | 31/147 [00:00<00:01, 70.66it/s]
 27%|██▋       | 39/147 [00:00<00:01, 70.07it/s]
 32%|███▏      | 47/147 [00:00<00:01, 63.89it/s]
 37%|███▋      | 54/147 [00:00<00:01, 57.45it/s]
 41%|████▏     | 61/147 [00:01<00:01, 60.42it/s]
 49%|████▉     | 72/147 [00:01<00:01, 73.05it/s]
 56%|█████▌    | 82/147 [00:01<00:00, 79.45it/s]
 63%|██████▎   | 93/147 [00:01<00:00, 84.54it/s]
 71%|███████   | 104/147 [00:01<00:00, 89.38it/s]
 78%|███████▊  | 114/147 [00:01<00:00, 92.32it/s]
 84%|████████▍ | 124/147 [00:01<00:00, 94.04it/s]
 92%|█████████▏| 135/147 [00:01<00:00, 94.51it/s]
100%|██████████| 147/147 [00:01<00:00, 78.66it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Profiling table: raw_crs04_cap200

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/523 [00:00<?, ?it/s]
  2%|▏         | 8/523 [00:00<00:06, 78.18it/s]
  3%|▎         | 16/523 [00:00<00:08, 61.90it/s]
  6%|▌         | 29/523 [00:00<00:05, 83.80it/s]
  8%|▊         | 41/523 [00:00<00:05, 94.60it/s]
 10%|█         | 53/523 [00:00<00:04, 100.66it/s]
 12%|█▏        | 64/523 [00:00<00:04, 102.73it/s]
 14%|█▍        | 75/523 [00:00<00:04, 101.35it/s]
 16%|█▋        | 86/523 [00:00<00:04, 103.54it/s]
 19%|█▊        | 97/523 [00:01<00:04, 100.37it/s]
 21%|██        | 110/523 [00:01<00:03, 105.73it/s]
 23%|██▎       | 122/523 [00:01<00:03, 104.15it/s]
 25%|██▌       | 133/523 [00:01<00:03, 105.37it/s]
 28%|██▊       | 145/523 [00:01<00:03, 106.67it/s]
 30%|███       | 157/523 [00:01<00:03, 107.52it/s]
 32%|███▏      | 169/523 [00:01<00:03, 107.70it/s]
 34%|███▍      | 180/523 [00:01<00:03, 107.66it/s]
 37%|███▋      | 191/523 [00:01<00:03, 103.65it/s]
 39%|███▊      | 202/523 [00:02<00:03, 98.98it/s]
 41%|████      | 213/523 [00:02<00:03, 100.76it/s]
 43%|████▎     | 224/523 [00:02<00:03, 98.59it/s]
 45%|████▌     | 236/523 [00:02<00:02, 96.35it/s]
 47%|████▋     | 247/523 [00:02<00:02, 97.30it/s]
 50%|████▉     | 259/523 [00:02<00:02, 102.72it/s]
 52%|█████▏    | 270/523 [00:02<00:02, 103.53it/s]
 54%|█████▎    | 281/523 [00:02<00:02, 104.95it/s]
 56%|█████▌    | 292/523 [00:02<00:02, 102.53it/s]
 58%|█████▊    | 303/523 [00:03<00:02, 102.59it/s]
 60%|██████    | 314/523 [00:03<00:02, 97.16it/s]
 62%|██████▏   | 326/523 [00:03<00:01, 102.24it/s]
 64%|██████▍   | 337/523 [00:03<00:01, 99.77it/s]
 67%|██████▋   | 348/523 [00:03<00:01, 101.20it/s]
 69%|██████▊   | 359/523 [00:03<00:01, 96.44it/s]
 71%|███████   | 372/523 [00:03<00:01, 101.24it/s]
 73%|███████▎  | 384/523 [00:03<00:01, 100.08it/s]/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

 76%|███████▌  | 398/523 [00:03<00:01, 110.30it/s]
 78%|███████▊  | 410/523 [00:04<00:01, 106.10it/s]
 80%|████████  | 421/523 [00:04<00:01, 99.57it/s]
 83%|████████▎ | 432/523 [00:04<00:00, 99.27it/s]
 85%|████████▍ | 443/523 [00:04<00:00, 97.91it/s]
 87%|████████▋ | 455/523 [00:04<00:00, 102.16it/s]
 89%|████████▉ | 466/523 [00:04<00:00, 100.73it/s]
 91%|█████████ | 477/523 [00:04<00:00, 100.05it/s]
 93%|█████████▎| 488/523 [00:04<00:00, 99.88it/s]
 95%|█████████▌| 499/523 [00:04<00:00, 99.80it/s]
 98%|█████████▊| 511/523 [00:05<00:00, 102.36it/s]
100%|██████████| 523/523 [00:05<00:00, 100.67it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Profiling table: raw_crs04_cap248

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/578 [00:00<?, ?it/s]
  1%|          | 6/578 [00:00<00:10, 57.14it/s]
  2%|▏         | 12/578 [00:00<00:10, 54.87it/s]
  3%|▎         | 19/578 [00:00<00:09, 60.06it/s]
  4%|▍         | 26/578 [00:00<00:08, 62.23it/s]
  6%|▌         | 35/578 [00:00<00:07, 71.05it/s]
  8%|▊         | 45/578 [00:00<00:06, 79.76it/s]
  9%|▉         | 54/578 [00:00<00:06, 79.93it/s]
 11%|█         | 63/578 [00:00<00:06, 82.28it/s]
 13%|█▎        | 73/578 [00:00<00:06, 83.34it/s]
 14%|█▍        | 82/578 [00:01<00:05, 83.19it/s]
 16%|█▌        | 91/578 [00:01<00:05, 82.76it/s]
 17%|█▋        | 100/578 [00:01<00:05, 84.23it/s]
 19%|█▉        | 111/578 [00:01<00:05, 89.30it/s]
 21%|██        | 121/578 [00:01<00:05, 87.36it/s]
 23%|██▎       | 133/578 [00:01<00:04, 93.09it/s]
 25%|██▍       | 144/578 [00:01<00:04, 95.52it/s]
 27%|██▋       | 154/578 [00:01<00:04, 92.50it/s]
 28%|██▊       | 164/578 [00:01<00:04, 90.80it/s]
 30%|███       | 174/578 [00:02<00:04, 91.03it/s]
 32%|███▏      | 184/578 [00:02<00:04, 87.60it/s]
 33%|███▎      | 193/578 [00:02<00:04, 87.60it/s]
 35%|███▍      | 202/578 [00:02<00:04, 87.21it/s]
 37%|███▋      | 211/578 [00:02<00:04, 86.86it/s]
 38%|███▊      | 220/578 [00:02<00:04, 86.26it/s]
 40%|███▉      | 231/578 [00:02<00:03, 92.95it/s]
 42%|████▏     | 241/578 [00:02<00:03, 90.22it/s]
 43%|████▎     | 251/578 [00:02<00:03, 87.10it/s]
 45%|████▌     | 261/578 [00:03<00:03, 87.02it/s]
 47%|████▋     | 271/578 [00:03<00:03, 87.69it/s]
 48%|████▊     | 280/578 [00:03<00:03, 86.70it/s]
 50%|█████     | 290/578 [00:03<00:03, 87.24it/s]
 52%|█████▏    | 301/578 [00:03<00:03, 89.08it/s]
 54%|█████▍    | 311/578 [00:03<00:02, 91.45it/s]
 56%|█████▌    | 321/578 [00:03<00:02, 92.90it/s]
 57%|█████▋    | 331/578 [00:03<00:02, 94.36it/s]
 59%|█████▉    | 341/578 [00:03<00:02, 93.12it/s]
 61%|██████    | 351/578 [00:04<00:02, 93.11it/s]
 62%|██████▏   | 361/578 [00:04<00:02, 93.32it/s]
 64%|██████▍   | 372/578 [00:04<00:02, 94.59it/s]/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

 66%|██████▌   | 382/578 [00:04<00:02, 90.20it/s]/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

 68%|██████▊   | 392/578 [00:04<00:02, 88.31it/s]/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4008: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

 70%|██████▉   | 402/578 [00:04<00:01, 90.16it/s]
 71%|███████▏  | 412/578 [00:04<00:01, 90.66it/s]
 73%|███████▎  | 422/578 [00:04<00:01, 92.28it/s]
 75%|███████▍  | 432/578 [00:04<00:01, 90.53it/s]
 76%|███████▋  | 442/578 [00:05<00:01, 91.27it/s]
 78%|███████▊  | 452/578 [00:05<00:01, 90.55it/s]
 80%|███████▉  | 462/578 [00:05<00:01, 86.86it/s]
 82%|████████▏ | 472/578 [00:05<00:01, 88.36it/s]
 83%|████████▎ | 482/578 [00:05<00:01, 90.35it/s]
 85%|████████▌ | 492/578 [00:05<00:00, 88.50it/s]
 87%|████████▋ | 501/578 [00:05<00:00, 88.24it/s]
 89%|████████▉ | 513/578 [00:05<00:00, 93.03it/s]
 90%|█████████ | 523/578 [00:05<00:00, 94.06it/s]
 92%|█████████▏| 533/578 [00:06<00:00, 92.87it/s]
 94%|█████████▍| 543/578 [00:06<00:00, 88.49it/s]
 96%|█████████▌| 552/578 [00:06<00:00, 88.76it/s]
 97%|█████████▋| 561/578 [00:06<00:00, 87.91it/s]
100%|██████████| 578/578 [00:06<00:00, 87.74it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Profiling table: raw_crs04_cap300

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/51 [00:00<?, ?it/s]
 16%|█▌        | 8/51 [00:00<00:00, 65.29it/s]
 29%|██▉       | 15/51 [00:00<00:00, 59.09it/s]
 49%|████▉     | 25/51 [00:00<00:00, 71.56it/s]
 69%|██████▊   | 35/51 [00:00<00:00, 81.25it/s]
100%|██████████| 51/51 [00:00<00:00, 79.23it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

,table_name,table_ref,profile_limit,profiled_rows,rowcount_before,rowcount_after,raw_data_unchanged,profile_output,profile_exists,profile_size_bytes,checked_at_utc
0,raw_crs04_cap100,enares-2024-crs04.enares2024_crs04_raw.raw_crs...,5000,5000,18807,18807,True,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,True,11621437,2026-06-19T23:31:36.990760+00:00
1,raw_crs04_cap200,enares-2024-crs04.enares2024_crs04_raw.raw_crs...,5000,5000,18807,18807,True,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,True,17556486,2026-06-19T23:31:36.990760+00:00
2,raw_crs04_cap248,enares-2024-crs04.enares2024_crs04_raw.raw_crs...,5000,5000,18807,18807,True,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,True,18215616,2026-06-19T23:31:36.990760+00:00
3,raw_crs04_cap300,enares-2024-crs04.enares2024_crs04_raw.raw_crs...,5000,5000,18807,18807,True,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,True,4534927,2026-06-19T23:31:36.990760+00:00

Issue #14 profiling PASS
Saved: /content/drive/MyDrive/ENARES_2024_PROJECT/05Resultados/logs/ENARES_2024_STAGE2_profiling_validation.csv

## 7. Cierre Notebook 06

Consolida los artefactos generados por este notebook.

In [ ]:
required_notebook06_outputs = [
    f"{DOCS_DIR}/ENARES_2024_STAGE2_CRS04_ERD.md",
    f"{DOCS_DIR}/ENARES_2024_STAGE2_partitioning_strategy.md",
    f"{DOCS_DIR}/ENARES_2024_STAGE2_security_architecture.md",
    f"{LOG_DIR}/ENARES_2024_STAGE2_documentation_check.csv",
    f"{LOG_DIR}/ENARES_2024_STAGE2_profiling_validation.csv",
    f"{LOG_DIR}/ENARES_2024_STAGE2_documentation_profiling_policy.csv",
]

for table_name in RAW_TABLES:
    required_notebook06_outputs.append(
        f"{LOG_DIR}/ENARES_2024_STAGE2_profile_{table_name}.html"
    )

closure06_rows = []

for path in required_notebook06_outputs:
    closure06_rows.append({
        "path": path,
        "filename": os.path.basename(path),
        "exists": os.path.exists(path),
        "size_bytes": os.path.getsize(path) if os.path.exists(path) else None,
        "checked_at_utc": RUN_UTC,
    })

closure06 = pd.DataFrame(closure06_rows)
closure06["notebook06_output_pass"] = closure06["exists"]

closure06_output = f"{LOG_DIR}/ENARES_2024_STAGE2_documentation_profiling_closure_check.csv"
closure06.to_csv(closure06_output, index=False)

display(closure06)

if not closure06["exists"].all():
    missing = closure06.loc[~closure06["exists"], "filename"].tolist()
    raise FileNotFoundError("Faltan outputs del Notebook 06: " + ", ".join(missing))

stage2_documentation_profiling_pass = bool(closure06["exists"].all())

print("stage2_documentation_profiling_pass:", stage2_documentation_profiling_pass)
print("Saved:", closure06_output)
print("Notebook 06 completed successfully.")

,path,filename,exists,size_bytes,checked_at_utc,notebook06_output_pass
0,/content/drive/MyDrive/ENARES_2024_PROJECT/doc...,ENARES_2024_STAGE2_CRS04_ERD.md,True,1911,2026-06-19T23:31:36.990760+00:00,True
1,/content/drive/MyDrive/ENARES_2024_PROJECT/doc...,ENARES_2024_STAGE2_partitioning_strategy.md,True,1850,2026-06-19T23:31:36.990760+00:00,True
2,/content/drive/MyDrive/ENARES_2024_PROJECT/doc...,ENARES_2024_STAGE2_security_architecture.md,True,1835,2026-06-19T23:31:36.990760+00:00,True
3,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,ENARES_2024_STAGE2_documentation_check.csv,True,560,2026-06-19T23:31:36.990760+00:00,True
4,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,ENARES_2024_STAGE2_profiling_validation.csv,True,1190,2026-06-19T23:31:36.990760+00:00,True
5,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,ENARES_2024_STAGE2_documentation_profiling_pol...,True,374,2026-06-19T23:31:36.990760+00:00,True
6,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,ENARES_2024_STAGE2_profile_raw_crs04_cap100.html,True,11621437,2026-06-19T23:31:36.990760+00:00,True
7,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,ENARES_2024_STAGE2_profile_raw_crs04_cap200.html,True,17556486,2026-06-19T23:31:36.990760+00:00,True
8,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,ENARES_2024_STAGE2_profile_raw_crs04_cap248.html,True,18215616,2026-06-19T23:31:36.990760+00:00,True
9,/content/drive/MyDrive/ENARES_2024_PROJECT/05R...,ENARES_2024_STAGE2_profile_raw_crs04_cap300.html,True,4534927,2026-06-19T23:31:36.990760+00:00,True

stage2_documentation_profiling_pass: True
Saved: /content/drive/MyDrive/ENARES_2024_PROJECT/05Resultados/logs/ENARES_2024_STAGE2_documentation_profiling_closure_check.csv
Notebook 06 completed successfully.

## 8. Texto sugerido para reporte

Los documentos técnicos de Stage 02 consolidan el diseño lógico/físico CRS04, la estrategia de particionamiento futura y la arquitectura de seguridad. El profiling se ejecutó en modo solo lectura sobre tablas raw, generando reportes HTML sin alterar microdatos. Estas evidencias complementan la ingesta raw, metadata SPSS/PDF, observabilidad y linaje generados en notebooks previos.